# Generated by Django 4.1.7 on 2023-04-21 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=500)),
                ('estado_curso', models.BooleanField(default=False)),
                ('duracion_curso', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
