<<<<<<< HEAD
# Generated by Django 4.1.1 on 2023-09-09 14:24
=======
# Generated by Django 4.1.7 on 2023-09-09 14:23
>>>>>>> 12e8060650ace0f137f8dc015adbb9f55082b08a

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD
    dependencies = [
        ("AppCursos", "0001_initial"),
=======

    dependencies = [
        ('AppCursos', '0001_initial'),
>>>>>>> 12e8060650ace0f137f8dc015adbb9f55082b08a
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="clases",
            name="descripcion_clase",
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name="evaluaciones",
            name="descripcion_evaluacion",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="evaluaciones",
            name="instrucciones_evaluacion",
=======
            model_name='clases',
            name='descripcion_clase',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='evaluaciones',
            name='descripcion_evaluacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciones',
            name='instrucciones_evaluacion',
>>>>>>> 12e8060650ace0f137f8dc015adbb9f55082b08a
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
