# Generated by Django 4.1.7 on 2023-10-18 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppCursos', '0001_initial'),
        ('AppUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='id_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.cargo'),
        ),
        migrations.AddField(
            model_name='clases',
            name='id_modulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCursos.modulos'),
        ),
    ]
