# Generated by Django 4.1.7 on 2023-09-09 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clases',
            name='descripcion_clase',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='evaluaciones',
            name='descripcion_evaluacion',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='evaluaciones',
            name='instrucciones_evaluacion',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
    ]
