# Generated by Django 4.1.7 on 2023-09-27 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0002_cursos_id_cargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clases',
            old_name='nombre_modulo',
            new_name='id_modulo',
        ),
        migrations.RenameField(
            model_name='evaluaciones',
            old_name='nombre_modulo',
            new_name='id_modulo',
        ),
        migrations.RenameField(
            model_name='modulos',
            old_name='nombre_curso',
            new_name='id_curso',
        ),
        migrations.RenameField(
            model_name='preguntas',
            old_name='nombre_evaluacion',
            new_name='id_evaluacion',
        ),
    ]
