# Generated by Django 4.1.7 on 2023-04-22 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0003_cursos_iconocurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_modulo', models.CharField(max_length=100)),
                ('estado_modulo', models.BooleanField(default=False)),
                ('nombre_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCursos.cursos')),
            ],
            options={
                'verbose_name_plural': 'Modulos',
            },
        ),
    ]
