# Generated by Django 4.1.7 on 2023-09-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0003_rename_nombre_modulo_clases_id_modulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clases',
            name='orden_clase',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
