# Generated by Django 4.1.7 on 2023-04-22 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0004_modulos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='duracion_curso',
            field=models.IntegerField(blank=True),
        ),
    ]
