# Generated by Django 4.1.7 on 2023-09-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0004_clases_orden_clase'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulos',
            name='orden_modulo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
