# Generated by Django 4.1.7 on 2023-09-29 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0005_modulos_orden_modulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialApoyo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idmaterial', models.IntegerField()),
                ('NombreMaterialApoyo', models.CharField(max_length=255)),
                ('DescripcionMaterialApoyo', models.TextField()),
                ('Archivo', models.URLField()),
            ],
        ),
    ]
