# Generated by Django 4.1.7 on 2023-04-22 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0006_alter_cursos_duracion_curso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='descripcion',
            new_name='descripcion_curso',
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_clase', models.CharField(max_length=100)),
                ('duracion_clase', models.IntegerField(blank=True, null=True)),
                ('contenido_clase', models.URLField()),
                ('descripcion_clase', models.CharField(max_length=500)),
                ('estado_clase', models.BooleanField(default=False)),
                ('nombre_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCursos.modulos')),
            ],
            options={
                'verbose_name_plural': 'Clases',
            },
        ),
    ]
