# Generated by Django 4.1.7 on 2023-10-01 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0006_materialapoyo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cursos',
            name='id_cargo',
        ),
    ]
