# Generated by Django 4.1.7 on 2023-09-30 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0006_materialapoyo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialapoyo',
            name='idmaterial',
        ),
        migrations.AddField(
            model_name='materialapoyo',
            name='id_curso',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCursos.cursos'),
        ),
    ]
