# Generated by Django 4.1.7 on 2023-07-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0007_rename_descripcion_cursos_descripcion_curso_clases'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='iconoCurso',
            field=models.ImageField(blank=True, null=True, upload_to='IconosCurso'),
        ),
    ]
