# Generated by Django 4.1.7 on 2023-10-01 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0006_remove_cargo_id_cursos'),
        ('AppCursos', '0007_remove_cursos_id_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cursos',
            name='id_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.cargo'),
        ),
    ]
