# Generated by Django 4.1.7 on 2023-07-05 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0007_rename_descripcion_cursos_descripcion_curso_clases'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_evaluacion', models.CharField(max_length=100)),
                ('duracion_evaluacion', models.TimeField(blank=True, null=True)),
                ('nombre_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCursos.modulos')),
            ],
            options={
                'verbose_name_plural': 'Evaluaciones',
            },
        ),
        migrations.AlterField(
            model_name='cursos',
            name='iconoCurso',
            field=models.ImageField(blank=True, null=True, upload_to='IconosCurso'),
        ),
        migrations.CreateModel(
            name='Preguntas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_pregunta', models.CharField(max_length=100)),
                ('nombre_evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCursos.evaluaciones')),
            ],
            options={
                'verbose_name_plural': 'Preguntas',
            },
        ),
    ]
