# Generated by Django 4.1.7 on 2023-10-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0007_remove_materialapoyo_idmaterial_and_more'),
        ('AppCursos', '0008_cursos_id_cargo'),
    ]

    operations = [
    ]
