# Generated by Django 4.1.7 on 2023-07-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0009_evaluaciones_descripcion_evaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciones',
            name='duracion_evaluacion_admin',
            field=models.IntegerField(default=30, max_length=3),
        ),
        migrations.AddField(
            model_name='evaluaciones',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='evaluaciones',
            name='instrucciones_evaluacion',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
