# Generated by Django 4.1.7 on 2023-07-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0010_evaluaciones_duracion_evaluacion_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluaciones',
            name='duracion_evaluacion_admin',
            field=models.IntegerField(default=30),
        ),
    ]
