# Generated by Django 4.1.7 on 2023-07-22 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0011_alter_evaluaciones_duracion_evaluacion_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluaciones',
            name='duracion_evaluacion',
        ),
        migrations.RemoveField(
            model_name='evaluaciones',
            name='finalizada',
        ),
    ]
