# Generated by Django 4.1.7 on 2023-10-11 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0011_rename_activo_cargos_estado_cargo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargos',
        ),
    ]
