# Generated by Django 4.1.7 on 2023-07-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0012_remove_evaluaciones_duracion_evaluacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='opcion_a',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='opcion_b',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='opcion_c',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='opcion_d',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='preguntas',
            name='respuesta_correcta',
            field=models.CharField(blank=True, choices=[('a', 'A'), ('b', 'B'), ('c', 'C'), ('d', 'D')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='preguntas',
            name='nombre_pregunta',
            field=models.TextField(max_length=100),
        ),
    ]
