# Generated by Django 4.1.7 on 2023-07-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0008_alter_cursos_iconocurso'),
        ('AppCursos', '0013_preguntas_opcion_a_preguntas_opcion_b_and_more'),
    ]

    operations = [
    ]
