# Generated by Django 4.1.7 on 2023-09-02 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0014_merge_20230722_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluaciones',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
