# Generated by Django 4.1.7 on 2023-10-18 22:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AppCursos', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100)),
                ('estado_cargo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Usuario_Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.cargo')),
                ('id_usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cargo_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Usuario_Cargo',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(blank=True, max_length=30, null=True, verbose_name='Apellido')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('estadousuario', models.BooleanField(default=True, verbose_name='Estado de Usuario')),
                ('role', models.CharField(blank=True, choices=[('usuario', 'Usuario'), ('administrador', 'Administrador')], max_length=15, null=True, verbose_name='Rol')),
                ('cargo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='AppUsuarios.cargo', verbose_name='Cargo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Clase_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visto', models.BooleanField(default=False)),
                ('id_clase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCursos.clases')),
                ('id_modulo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCursos.modulos')),
                ('id_usuario_cargo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.usuario_cargo')),
            ],
            options={
                'verbose_name_plural': 'Clase_Usuario',
            },
        ),
    ]
