# Generated by Django 4.1.7 on 2023-09-27 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0003_rename_nombre_modulo_clases_id_modulo_and_more'),
        ('AppUsuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clase_Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppCursos.modulos')),
                ('id_usuario_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.usuario_cargo')),
            ],
        ),
    ]
