# Generated by Django 4.1.7 on 2023-10-22 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0002_alter_profile_options_rename_role_profile_rol_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase_usuario',
            name='id_usuario_cargo',
        ),
        migrations.AddField(
            model_name='usuario_cargo',
            name='clases_usuario',
            field=models.ManyToManyField(to='AppUsuarios.clase_usuario'),
        ),
    ]
