# Generated by Django 4.1.7 on 2023-09-27 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0003_rename_nombre_modulo_clases_id_modulo_and_more'),
        ('AppUsuarios', '0002_clase_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clase_usuario',
            options={'verbose_name_plural': 'Clase_Usuario'},
        ),
        migrations.AddField(
            model_name='clase_usuario',
            name='id_clase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCursos.clases'),
        ),
        migrations.AddField(
            model_name='clase_usuario',
            name='visto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='clase_usuario',
            name='id_modulo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppCursos.modulos'),
        ),
        migrations.AlterField(
            model_name='clase_usuario',
            name='id_usuario_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.usuario_cargo'),
        ),
    ]
