# Generated by Django 4.1.7 on 2023-10-22 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0003_remove_clase_usuario_id_usuario_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_cargo',
            name='clases_usuario',
        ),
        migrations.AddField(
            model_name='clase_usuario',
            name='id_usuario_cargo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='AppUsuarios.usuario_cargo'),
        ),
    ]
