# Generated by Django 4.1.7 on 2023-10-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCursos', '0007_remove_cursos_id_cargo'),
        ('AppUsuarios', '0004_usuario_cargo_id_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario_cargo',
            name='id_cursos',
        ),
        migrations.AddField(
            model_name='cargo',
            name='id_cursos',
            field=models.ManyToManyField(blank=True, to='AppCursos.cursos'),
        ),
    ]
