# Generated by Django 4.1.7 on 2023-10-01 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0005_remove_usuario_cargo_id_cursos_cargo_id_cursos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cargo',
            name='id_cursos',
        ),
    ]
