# Generated by Django 4.1.7 on 2023-12-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppUsuarios', '0005_clase_usuario_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clase_usuario',
            name='tipo',
        ),
    ]
